---
resources:
- name: concourse-resources
  type: git
  source:
    uri: https://github.com/mghfdez/concourse-resources.git
    branch: master

- name: perceval-repo
  type: git
  source:
    uri: https://github.com/grimoirelab/perceval
    branch: master

- name: my-timer
  type: time
  source:
    interval: 2m

jobs:

- name: job-run-perceval
  public: true
  plan:
  - get: my-timer
  - get: concourse-resources
  - get: perceval-repo
  - task: run-perceval
    file: concourse-resources/config/install-perceval.yml
    input_mapping:
        my_resources: concourse-resources
        my_perceval: perceval-repo
