---
platform: linux

image_resource:
  type: docker-image
  source: {repository: frolvlad/alpine-python3}

inputs:
- name: my_resources
- name: my_perceval

run:
  path: ./my_resources/task-scripts/install_perceval.sh
