---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: python
    tag: 3.4

inputs:
- name: perceval-repo

run:
  path: sh
  args:
  - -exc
  - |
    cd perceval-repo
    pip3 install -r requirements.txt
    pip3 install httpretty==0.8.6
    pip3 install .
    cd tests
    python3 run_tests.py
