---
platform: linux

image_resource:
  type: docker-image
  source: {repository: grimoirelab/perceval}

inputs:
- name: my_resources
- name: my_perceval

run:
  path: ./my_resources/task-scripts/run_perceval.sh
