---
platform: linux

image_resource:
  type: docker-image
  source: {repository: frolvlad/alpine-python3}

inputs:
- name: miparametro

run:
  path: python3
  args: [miparametro/task-scripts/file_example.py]
